check applicability of mvs repr/color
molstar/molstar pull request #1012
Opened 2024-01-02 21:26 UTC by arose

# Description

## Actions

- [ ] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [ ] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`

2024-01-02 21:27 UTC, arose commented
@midlik made some tweaks to the MVS extensions so that the MVS related representations and color themes are only applicable (show up in the UI) when the structure has a model with a MVSAnnotationsProvider.

2024-01-03 13:38 UTC, midlik commented
Hi @arose , your change makes sense but only for `annotation-color-theme` and `annotation-label`. 
For `custom-label` and `multilayer-color-theme` it doesn't make sense, as these do not use `MVSAnnotationsProvider` and thus should be applicable always.

2024-01-03 13:50 UTC, midlik commented
Another thing is: your implementation only checks that the provider is there, but not if it has a non-empty list of annotation sources. The check should probably look more like this:

```
        // isApplicable: (ctx: ThemeDataContext) => !!ctx.structure?.models.some(m => m.customProperties.has(MVSAnnotationsProvider.descriptor)),
        isApplicable: (ctx: ThemeDataContext) => !!ctx.structure?.models.some(m => m.customProperties.has(MVSAnnotationsProvider.descriptor) && MVSAnnotationsProvider.props(m).annotations.length > 0),
```

Note: MVS load function is currently implemented in such a way that it always adds a MVSAnnotationsProvider custom property, even when the list of annotation sources is empty. Therefore your `isApplicable` always returns true if the model has been loaded via the MVS load function.

2024-01-03 13:59 UTC, midlik requested changes

2024-01-03 13:59 UTC, midlik commented on src/extensions/mvs/components/annotation-color-theme.ts
> +    isApplicable: (ctx: ThemeDataContext) => !!ctx.structure?.models.some(m => m.customProperties.has(MVSAnnotationsProvider.descriptor)),
I would make it:
```
isApplicable: (ctx: ThemeDataContext) => !!ctx.structure?.models.some(m => m.customProperties.has(MVSAnnotationsProvider.descriptor) && MVSAnnotationsProvider.props(m).annotations.length > 0),
```

2024-01-03 13:59 UTC, midlik commented on src/extensions/mvs/components/annotation-label/representation.ts
> +    isApplicable: (structure: Structure) => structure.elementCount > 0 && !!structure.models.some(m => m.customProperties.has(MVSAnnotationsProvider.descriptor)),
I would make it:
```
isApplicable: (ctx: ThemeDataContext) => structure.elementCount > 0 && !!structure.models.some(m => m.customProperties.has(MVSAnnotationsProvider.descriptor) && MVSAnnotationsProvider.props(m).annotations.length > 0),
```

2024-01-03 13:59 UTC, midlik commented on src/extensions/mvs/components/custom-label/representation.ts
> +    isApplicable: (structure: Structure) => structure.elementCount > 0 && !!structure.models.some(m => m.customProperties.has(MVSAnnotationsProvider.descriptor)),
I would revert this change, CustomLabelRepresentationProvider should be applicable even without MVSAnnotationsProvider.

(That's also the reason I didn't use the 'MVS ' prefix in the label, but I don't have a strong opinion about it)

2024-01-03 13:59 UTC, midlik commented on src/extensions/mvs/components/multilayer-color-theme.ts
> +        isApplicable: (ctx: ThemeDataContext) => !!ctx.structure?.models.some(m => m.customProperties.has(MVSAnnotationsProvider.descriptor)),
I would revert this change, makeMultilayerColorThemeProvider should be applicable even without MVSAnnotationsProvider.

(That's also the reason I didn't use the 'MVS ' prefix in the label, but I don't have a strong opinion about it)

2024-01-03 17:28 UTC, arose commented
@midlik I would like to separate the reprs/themes from non-MVS use. My thinking is that we either have something generic that can be in core (or maybe a generic extension). Since the 'mvs-multilayer' color theme and 'mvs-custom-label' representation are custom for the mvs extension I would like them to only be applicable in the MVS context. Instead of the MVSAnnotationsProvider I am OK to add some other custom property to a model/structure to mark them as being used in the MVS context.

2024-01-05 17:25 UTC, arose commented
@midlik what do you think of adding some kind of MVS property to mark models as being used in a MVS context? Would you propose it? Or just use MVSAnnotationsProvider for now?

2024-01-06 11:08 UTC, midlik commented
Hi, now I see you point.
The solution with a "MVS flag" custom property makes sense, I'm just not sure if it's worth it to introduce a new property just for this. I'll discuss this with @dsehnal (we have a meeting on Monday) and let you know.

2024-01-06 14:55 UTC, dsehnal commented
I think having 

```ts
const IsMVSProperty = {  // using object to avoid namespace
  set(m: Model) {
    m._staticPropertyData._isMVS_ = true;
  },
  get(m: Model) {
    return !!m._staticPropertyData._isMVS_;
  }
}
```

and setting this for all models that have been added by the extension would be a good solution.

One way to automate this would be to set `mvs-model` tag when adding the model nodes (`.apply(..., { tags: ['mvs-model'] });` and  then `plugin.state.data.selectQ(q => q.root.subtree().withTag('mvs-model')).forEach(cell => IsMVSProperty.set(cell.obj?.data))`... or just keep the list of model refs when constructing the tree.

2024-01-09 09:20 UTC, midlik commented
I will implement the "MVS flag" custom property and create a separate PR.

2024-01-09 11:55 UTC, midlik commented
I created the alternative PR: https://github.com/molstar/molstar/pull/1022

2024-01-11 06:14 UTC, arose commented
> Now I'm thinking that the "Custom Label" 3D representation could find some use cases even outside the MVS context.

there is also the Label option in the Measurement section that offers similar functionality, maybe that can be extended if need be?

2024-01-11 06:14 UTC, arose commented
closing in favor of #1022

2024-01-11 06:14 UTC, closed without merging

2024-01-11 13:21 UTC, midlik commented
> > Now I'm thinking that the "Custom Label" 3D representation could find some use cases even outside the MVS context.
> 
> there is also the Label option in the Measurement section that offers similar functionality, maybe that can be extended if need be?

Oh, I was not aware of that.
Then ignore my suggestion.