update mesh positionIt
molstar/molstar pull request #1072
Opened 2024-03-27 09:45 UTC by hui2000ji

# Description

This is an initial attempt to fix #1071. It is **NOT READY FOR MERGING** yet.

- With this fix enabled, all surface will be coloured by function values 1.4A away from the point on surface ("away" means the direction of the normal vector at this point). This value is now hard-coded. Ideally, the user should be able to enable/disable this behaviour and configure the value 1.4A.
- I only tested on "Molecular Surface Mesh" and did not check the behaviour on the other two types of molecular surface visualization.

![image](https://github.com/molstar/molstar/assets/32122441/28fbeb95-bc2a-4bc7-b658-0ef8deb6c4d1)

# How I come up with this fix

Below is a brief description on how creating a Molecular Surface with a UnitsMeshVisual works.

- `mol-repr/structure/visual/molecular-surface-mesh.ts`: This is the entry point of creating a molecular surface. It invokes `UnitsMeshVisual`.
- `mol-repr/structure/units-visual.ts`: Where `UnitsMeshVisual` is defined. It invokes:
    - `positionIt = createPositionIterator(newGeometry, renderObject.values)`
        - Type definitions: Mesh, TransformData -> LocationIterator
        - Implemented in `mol-geo/geometry/mesh/mesh.ts`
    - `createColors(locationIt, positionIt, newTheme.color, renderObject.values)`
        - Type definitions: LocationIterator, LocationIterator, LocationColor, ColorData -> ColorData
        - Implemented in `mol-geo/geometry/color-data.ts`
    - The `color` function, of type LocationColor, is implemented in `mol-theme/color/external-volume.ts`
        - Type definitions: Location -> Color. Note that granularity is "vertex".

Note that `createColors` accept a location iterator and a position iterator. When creating colors when `colorTheme.granularity == 'vertex'` (which is the case for the External Volume theme), only the position iterator is used.
So the fix is done by changing the logic of `createPositionIterator`. Instead of returning the position for each point on the surface, it returns the position of a point that is 1.4A away from (moving by the direction of the normal vector at this point) the point on the surface.

## Actions

- [ ] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [ ] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`

2024-03-28 05:31 UTC, arose commented
I like this feature! I suggest to add the normal as an optional property to `PositionLocation` and do the normal + position in the color theme. That way you can make the `offset` value part of the color theme params.

2024-03-29 04:02 UTC, hui2000ji commented
Hi Alex! Thanks for your enlightening suggestions. I have made the corresponding changes. Please take a look.

2024-03-30 21:06 UTC, arose requested changes
Thanks @hui2000ji. I tested this with results from https://server.poissonboltzmann.org/ and it works very ncely. I made a few inline comments, but once those are adressed we can merge it.

2024-03-31 15:16 UTC, hui2000ji commented on src/mol-geo/geometry/mesh/mesh.ts
> +                Vec3.transformMat4Offset(n, ns, m, 0, groupIndex * 3, instanceIndex * 16);
Should I calculate the transpose of the inverse within this new method?

```typescript
/**
 * Transforms the direction vector with a Mat4. 4th vector component is implicitly '0'
 * This means the translation components of the matrix are ignored.
 * This function is useful for transforming normal vectors with non-uniform scaling.
 */
export function transformDirectionOffset(out: NumberArray, a: NumberArray, m: NumberArray, outO: number, aO: number, oM: number) {
    // Assumes that m is already the transpose of the inverse matrix suitable for normal transformation.
    const x = a[0 + aO], y = a[1 + aO], z = a[2 + aO];
    out[0 + outO] = m[0 + oM] * x + m[4 + oM] * y + m[8 + oM] * z;
    out[1 + outO] = m[1 + oM] * x + m[5 + oM] * y + m[9 + oM] * z;
    out[2 + outO] = m[2 + oM] * x + m[6 + oM] * y + m[10 + oM] * z;
    // Normalize the output vector to handle non-uniform scaling
    const len = Math.hypot(out[0 + outO], out[1 + outO], out[2 + outO]);
    if (len > 0) {
        out[0 + outO] /= len;
        out[1 + outO] /= len;
        out[2 + outO] /= len;
    }
    return out;
}
```

2024-03-31 17:28 UTC, arose commented on src/mol-geo/geometry/mesh/mesh.ts
> +                Vec3.transformMat4Offset(n, ns, m, 0, groupIndex * 3, instanceIndex * 16);
> Should I calculate the transpose of the inverse within this new method?

No, let's assume the transformation matrix is "well behaved". I will make an issue to pre-calculate the transpose of the inverse so it is available in the `TransformData` and we can use it here and also in the `mesh.vert.glsl` shader.

2024-04-01 02:24 UTC, hui2000ji commented
Hi @arose, I tried to address your comments. Please check if everything's good now.

2024-04-01 05:21 UTC, arose approved these changes

2024-04-01 05:25 UTC, merged

2024-04-01 05:25 UTC, arose commented
Thank you @hui2000ji, very nicely done!

2024-04-01 08:23 UTC, dsehnal commented
Good job @hui2000ji !