Add quantized lighting option
molstar/molstar pull request #1118
Opened 2024-05-06 13:37 UTC by giagitom

# Description
This PR adds quantized lighting at representation level. Here are some examples
![1TQN (1)](https://github.com/molstar/molstar/assets/20627977/daf38b71-27f2-4ea5-843b-c1ac53ae1c13)
![1TQN (2)](https://github.com/molstar/molstar/assets/20627977/2b30ccd1-1373-4113-bc88-f540b6a4aa2e)
![1TQN (3)](https://github.com/molstar/molstar/assets/20627977/d8eee3c0-2bfb-4e41-892f-1a5f6b4f8d31)

## Actions

- [x] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [ ] Updated headers of modified files
- [ ] Added my name to `package.json`'s `contributors`
- [ ] (Optional but encouraged) Improved documentation in `docs`

2024-05-06 13:40 UTC, giagitom commented
![image](https://github.com/molstar/molstar/assets/20627977/2c4b6d98-fde4-497a-8fbd-2d71b88ef494)

2024-05-12 15:25 UTC, arose commented
How about adding options for steps and tint? Something like in the patch below.

[quant-tweaks.diff.txt](https://github.com/molstar/molstar/files/15286790/quant-tweaks.diff.txt)

2024-05-12 15:26 UTC, arose requested changes
How about adding options for steps and tint? Something like in the patch below.

[quant-tweaks.diff.txt](https://github.com/molstar/molstar/files/15286795/quant-tweaks.diff.txt)

2024-05-13 19:03 UTC, giagitom commented
Nice, I added the tweaks

2024-06-08 11:04 UTC, giagitom commented
So i think this should be seen as an intermediate between shading and flat coloring. Like a toon shading maybe? Something similar without extra options is implemented in PyMol https://wiki.pymol.org/index.php/Ray. 
![image](https://github.com/molstar/molstar/assets/20627977/1f8f632f-320a-44d5-adb0-b138940506eb)

2024-06-09 08:54 UTC, giagitom commented
Maybe just keeping quantization steps without the extra color option would be better?

2024-06-11 04:57 UTC, arose commented
![image](https://github.com/molstar/molstar/assets/272250/5cec4dbd-90da-4a80-8397-666fd66165b3)

Got a proof of concept for cel-shading. We need to do it together with the light calculation so we get light intensities for the shading levels. If you do it afterwards only from color, dark colors get overly dark.

2024-06-11 10:08 UTC, giagitom commented
It is very nice! It much better preserves original colors

2024-06-16 19:49 UTC, arose commented
Hey, made this into a PR for Cel-shading

- Add Cel-shading support
    - `celShaded` geometry parameter
    - `celSteps` renderer parameter

You can get a "sketched" looking imaged by enabling `celShaded`, enabling `outline` and setting the `threshold` to 0.1, plus setting `bumpiness` to 0.2. The below image also has a bit of `emissive` for he residues in the center.

![image](https://github.com/molstar/molstar/assets/272250/45933d2b-63dd-4f89-b372-c5c1ddb08d40)

2024-06-16 19:49 UTC, arose approved these changes

2024-06-17 19:32 UTC, giagitom commented
Thanks @arose for the changes. It looks very nice!

2024-06-19 04:50 UTC, merged