Remove common protein caps from ligand query
molstar/molstar pull request #606
Opened 2022-11-02 10:01 UTC by jpattle

# Description
This change adds names of common protein caps (`NME` and `ACE`) and then excludes any residues (whether they are part of the protein or not) with those names from the query that selects the ligand. This means that proteins that have been capped with these residues will not show the caps as a part of the ligand component created by default. This also affects the `ligandPlusConnected` query similarly.

## Actions

- [Y] Added description of changes to the `[Unreleased]` section of `CHANGELOG.md`
- [NA] Updated headers of modified files
- [Y] Added my name to `package.json`'s `contributors`

2022-11-07 01:07 UTC, arose requested changes
Thanks @jpattle. I like the change but lets check with @JonStargaryen and @mandarsd if it is OK with them as well.

2022-11-07 08:37 UTC, jpattle commented on src/mol-plugin-state/helpers/structure-selection-query.ts
> +            MS.struct.modifier.wholeResidues({
Makes sense, thank you. I have pushed an update

2022-11-07 08:38 UTC, jpattle commented
> Thanks @jpattle. I like the change but lets check with @JonStargaryen and @mandarsd if it is OK with them as well.

Absolutely, happy to wait for it to be checked 🙂

2022-11-07 16:45 UTC, JonStargaryen commented
Nice change!
And thanks for checking :)

2022-11-21 08:59 UTC, jpattle commented
@arose looks like Jon has given the go-ahead, is this good to merge?

2022-11-22 07:08 UTC, arose commented
Was waiting for @mandarsd as a PDBe representative.

2022-12-03 18:40 UTC, arose commented
Going to merge it. We can always adjust if it is problematic. Thank you @jpattle.

2022-12-03 18:41 UTC, merged